### ISSUE TITLE
Enquiry about extract_secondary_structure

### ISSUE THREAD

**Issue by GRAPH-0** [tzok/rnapolis-py#105]
Hi @tzok,  thanks for your great repo!
As the document is missing, could you please tell me what method you use to extract the secondary structure?
It would be nice if you could provide a code example for extracting secondary structures from PDB files!

**Comment by tzok** [comment]
Dear @GRAPH-0, I apologize for the missing documentation. I assure you that I will create and update it regularly.

The program functions by detecting the presence of hydrogen bonds within a given system. Subsequently, it proceeds to map out the edges that are formed, categorizing them into three types - WC, H, or S - while also verifying whether they are of cis or trans type. Furthermore, the program also examines the interactions between the base and ribose/phosphate, identifying any relevant patterns.

The sample code is the following:

```python
structure3d = rnapolis.parser.read_3d_structure(cif_or_pdb)
structure2d = rnapolis.annotator.extract_secondary_structure(structure3d)
```

**Comment by GRAPH-0** [comment]
Thanks for your quick response! My questions have been resolved. Look forward to further improvement of this project!
