### ISSUE TITLE
Cached property and unexpected serialization

### ISSUE THREAD

**Issue by niz-ka** [tzok/rnapolis-py#31]
Hi,
I can see that `@cahed_property` comes with `rnapolis 0.0.10`  in `commons.py`. I didn't know this useful property. But there is a problem with that. Unlike `@property`, `@cached_property` behaves like normal instance attribute but with mechanism of caching. What wrong with that?

Assume that we have instance of `Residue` named `residue`.  If we call `residue.__dict__.keys()` and cache is empty we get: ``dict_keys(['label', 'auth'])``

But depending on what it is in cache we can also get for example:
- ``dict_keys(['label', 'auth', 'chain', 'number'])``
-  ``dict_keys(['label', 'auth', 'chain', ' molecule_type'])``
- ``dict_keys(['label', 'auth', 'chain', 'number',  'molecule_type'])``
- ...

So calling getter on `@cached_property`, e.g. `residue.number` make it regular attribute and our `__dict__` is ""dynamic".  When you use `orjson` you can get unexpected result:

```
"nt1": {
  "label": {
      "chain": "A",
      "number": 1,
      "name": "G"
  },
  "auth": {
      "chain": "A",
      "number": 1,
      "icode": null,
      "name": "G"
  },
  "chain": "A",
  "number": 1,
  "icode": null
}
```

Maybe you were aware of this behavior and you accept it. But if not - I cannot see any elegant solution (from adapters perspective :)): 
- Probably there is no way to exclude attribute in python in serialization (or I don't know that way)
- I've tried with `del` and `delattr` but of course `Residue` is `frozen`...
- Deep copy of `Residue` is time and memory wasting
- Some magic with `__dict__` or `__slots__` ? But it's too hard for me with my python knowledge
- Restore custom model in adapters
- Remove some `@cached_property` to the needs of adapters

Docs: https://docs.python.org/3/library/functools.html#functools.cached_property

**Comment by tzok** [comment]
@niz-ka Thank you, I was not aware of this and indeed it is a problem. I will add a "contract"-like unit tests to check for all properties using `__dict__` and then will look for solutions. The docs suggest that using `@property @cache` may solve it as it works a bit differently than `@cached_property`
